[{"TimeUTC":"2025-06-20 21:42:30","timestampInMs":1750455750526,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"z552r-1750455748904-86ecf31fd88c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MP2AFFYNS8X1CX6QV5D9G","instanceId":""},{"TimeUTC":"2025-06-20 21:42:28","timestampInMs":1750455748943,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"z552r-1750455748904-86ecf31fd88c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1558,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MP2AFFYNS8X1CX6QV5D9G","instanceId":""},{"TimeUTC":"2025-06-20 21:42:26","timestampInMs":1750455746828,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"gk7p9-1750455745199-63727fc06b8d","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNYPPPGVWX1XRFN7PRWNB","instanceId":""},{"TimeUTC":"2025-06-20 21:42:25","timestampInMs":1750455745237,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"gk7p9-1750455745199-63727fc06b8d","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1567,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNYPPPGVWX1XRFN7PRWNB","instanceId":""},{"TimeUTC":"2025-06-20 21:42:24","timestampInMs":1750455744925,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"bv6bb-1750455743277-a69edaafe8e8","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNWTXJQ1E1QWWBKAHKN3R","instanceId":""},{"TimeUTC":"2025-06-20 21:42:24","timestampInMs":1750455744144,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"dj8cr-1750455743061-57a4f8e30881","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNWKY8CZ5PH0QM6WSJA4D","instanceId":""},{"TimeUTC":"2025-06-20 21:42:23","timestampInMs":1750455743325,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"bv6bb-1750455743277-a69edaafe8e8","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1580,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNWTXJQ1E1QWWBKAHKN3R","instanceId":""},{"TimeUTC":"2025-06-20 21:42:23","timestampInMs":1750455743102,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"dj8cr-1750455743061-57a4f8e30881","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1024,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNWKY8CZ5PH0QM6WSJA4D","instanceId":""},{"TimeUTC":"2025-06-20 21:42:23","timestampInMs":1750455743022,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"tggv9-1750455741865-7138c73d741d","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNVEHCMV7J6QXXDM5XC3X","instanceId":""},{"TimeUTC":"2025-06-20 21:42:22","timestampInMs":1750455742184,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"7gh9q-1750455739988-4e08e8bd2201","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNSKW9B2B4W9WWP0PRBFY","instanceId":""},{"TimeUTC":"2025-06-20 21:42:21","timestampInMs":1750455741905,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"tggv9-1750455741865-7138c73d741d","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1102,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNVEHCMV7J6QXXDM5XC3X","instanceId":""},{"TimeUTC":"2025-06-20 21:42:20","timestampInMs":1750455740028,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"7gh9q-1750455739988-4e08e8bd2201","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1567,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNSKW9B2B4W9WWP0PRBFY","instanceId":""},{"TimeUTC":"2025-06-20 21:42:19","timestampInMs":1750455739782,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"tg997-1750455738189-9dd8777dcfe8","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNQVMH8J77DWTHS3EN3EN","instanceId":""},{"TimeUTC":"2025-06-20 21:42:19","timestampInMs":1750455739493,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"w565v-1750455738350-2e5d51ffc052","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNR0N3FE2C9CSZAC3S2M2","instanceId":""},{"TimeUTC":"2025-06-20 21:42:18","timestampInMs":1750455738389,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"w565v-1750455738350-2e5d51ffc052","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1090,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNR0N3FE2C9CSZAC3S2M2","instanceId":""},{"TimeUTC":"2025-06-20 21:42:18","timestampInMs":1750455738228,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"tg997-1750455738189-9dd8777dcfe8","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1532,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNQVMH8J77DWTHS3EN3EN","instanceId":""},{"TimeUTC":"2025-06-20 21:42:17","timestampInMs":1750455737062,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"5q9c5-1750455735448-cd800f9fb29b","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNN64CWBTY3BJSJTMJ1PG","instanceId":""},{"TimeUTC":"2025-06-20 21:42:16","timestampInMs":1750455736256,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"85mjw-1750455735115-d9b361a926e4","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNMW2R1B8GC3N8HTTMS5P","instanceId":""},{"TimeUTC":"2025-06-20 21:42:15","timestampInMs":1750455735492,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"5q9c5-1750455735448-cd800f9fb29b","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1553,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNN64CWBTY3BJSJTMJ1PG","instanceId":""},{"TimeUTC":"2025-06-20 21:42:15","timestampInMs":1750455735323,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"fgbff-1750455733664-4d66c40f260c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNKE587N14BVTY4XCBXK5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:15","timestampInMs":1750455735170,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"85mjw-1750455735115-d9b361a926e4","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1068,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNMW2R1B8GC3N8HTTMS5P","instanceId":""},{"TimeUTC":"2025-06-20 21:42:14","timestampInMs":1750455734022,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"fgbff-1750455732798-a055dab60828","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNJK5MJ0Q1EQXQMWGABBB","instanceId":""},{"TimeUTC":"2025-06-20 21:42:13","timestampInMs":1750455733701,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"fgbff-1750455733664-4d66c40f260c","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1602,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNKE587N14BVTY4XCBXK5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:12","timestampInMs":1750455732837,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.png","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"fgbff-1750455732798-a055dab60828","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1170,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNJK5MJ0Q1EQXQMWGABBB","instanceId":""},{"TimeUTC":"2025-06-20 21:42:12","timestampInMs":1750455732758,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"22bl6-1750455731480-0486cd3d0e57","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNHA9SEPZNBMT2MHH7ZAG","instanceId":""},{"TimeUTC":"2025-06-20 21:42:12","timestampInMs":1750455732580,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"v2qgz-1750455730930-56a485574c89","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNGRV3Q273SW6VWNZ9CGM","instanceId":""},{"TimeUTC":"2025-06-20 21:42:11","timestampInMs":1750455731529,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"22bl6-1750455731480-0486cd3d0e57","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1200,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNHA9SEPZNBMT2MHH7ZAG","instanceId":""},{"TimeUTC":"2025-06-20 21:42:10","timestampInMs":1750455730971,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"v2qgz-1750455730930-56a485574c89","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1583,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNGRV3Q273SW6VWNZ9CGM","instanceId":""},{"TimeUTC":"2025-06-20 21:42:10","timestampInMs":1750455730062,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"t64xg-1750455727644-d44eecce34d4","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNDJ3S6M27N4K4Z994P93","instanceId":""},{"TimeUTC":"2025-06-20 21:42:09","timestampInMs":1750455729520,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"9mrnl-1750455728362-c54fc4774d8f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNE8GM6ZYBED4BJY09HT7","instanceId":""},{"TimeUTC":"2025-06-20 21:42:09","timestampInMs":1750455729385,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"88tjk-1750455728210-2106d56350a7","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNE4N02F4CQ4288K89XVA","instanceId":""},{"TimeUTC":"2025-06-20 21:42:08","timestampInMs":1750455728400,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"9mrnl-1750455728362-c54fc4774d8f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1101,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNE8GM6ZYBED4BJY09HT7","instanceId":""},{"TimeUTC":"2025-06-20 21:42:08","timestampInMs":1750455728277,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"88tjk-1750455728210-2106d56350a7","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1084,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNE4N02F4CQ4288K89XVA","instanceId":""},{"TimeUTC":"2025-06-20 21:42:08","timestampInMs":1750455728048,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"fhpt9-1750455726893-5fa8c1ad9f1b","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNCTKPT3W1JJFG0G8HE0F","instanceId":""},{"TimeUTC":"2025-06-20 21:42:07","timestampInMs":1750455727683,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"t64xg-1750455727644-d44eecce34d4","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1603,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNDJ3S6M27N4K4Z994P93","instanceId":""},{"TimeUTC":"2025-06-20 21:42:07","timestampInMs":1750455727544,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"99nt5-1750455724655-d6269fd0189f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"ib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNAMMEWYQV71246NSQQ22","instanceId":""},{"TimeUTC":"2025-06-20 21:42:07","timestampInMs":1750455727145,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"j4kr4-1750455725769-2baa8a4104ce","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNBQJ201JAP471ZBY5A5K","instanceId":""},{"TimeUTC":"2025-06-20 21:42:06","timestampInMs":1750455726930,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"fhpt9-1750455726893-5fa8c1ad9f1b","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1099,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNCTKPT3W1JJFG0G8HE0F","instanceId":""},{"TimeUTC":"2025-06-20 21:42:06","timestampInMs":1750455726913,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"tg997-1750455725774-8659cfb1a55a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNBQP2SSQFNSMKDTJ7DFE","instanceId":""},{"TimeUTC":"2025-06-20 21:42:06","timestampInMs":1750455726736,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"cxpcc-1750455725621-26f40f03de91","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNBJWHGKK395FF1DCXXS6","instanceId":""},{"TimeUTC":"2025-06-20 21:42:06","timestampInMs":1750455726684,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"k86rq-1750455723399-32c86b42c87f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"b/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN9DJQBMKSWYEFVPDNCPC","instanceId":""},{"TimeUTC":"2025-06-20 21:42:05","timestampInMs":1750455725814,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"tg997-1750455725774-8659cfb1a55a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1085,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNBQP2SSQFNSMKDTJ7DFE","instanceId":""},{"TimeUTC":"2025-06-20 21:42:05","timestampInMs":1750455725810,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"j4kr4-1750455725769-2baa8a4104ce","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1317,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNBQJ201JAP471ZBY5A5K","instanceId":""},{"TimeUTC":"2025-06-20 21:42:05","timestampInMs":1750455725660,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/favicon.ico","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"cxpcc-1750455725621-26f40f03de91","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1060,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNBJWHGKK395FF1DCXXS6","instanceId":""},{"TimeUTC":"2025-06-20 21:42:05","timestampInMs":1750455725634,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"hsmkf-1750455724494-403f876ecab4","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNAFS4NZMCH8CQZT8KXTJ","instanceId":""},{"TimeUTC":"2025-06-20 21:42:05","timestampInMs":1750455725540,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"c6hh2-1750455724106-a8e6e01420e1","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNA7VM0ZHSDJ83DPCNVWP","instanceId":""},{"TimeUTC":"2025-06-20 21:42:05","timestampInMs":1750455725425,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"4zvnx-1750455724173-01bfba7c00f7","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNAA0RCRR1KP934638SGE","instanceId":""},{"TimeUTC":"2025-06-20 21:42:04","timestampInMs":1750455724935,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"2wfz4-1750455722200-121e391d8e8e","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"2/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN8BNY2TT51YMDECHKXV5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:04","timestampInMs":1750455724692,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"99nt5-1750455724655-d6269fd0189f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1638,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNAMMEWYQV71246NSQQ22","instanceId":""},{"TimeUTC":"2025-06-20 21:42:04","timestampInMs":1750455724537,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"hsmkf-1750455724494-403f876ecab4","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1071,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNAFS4NZMCH8CQZT8KXTJ","instanceId":""},{"TimeUTC":"2025-06-20 21:42:04","timestampInMs":1750455724534,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"4dcbg-1750455723378-04c58c29f329","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN9CYWD0WPFKCJ492HYX5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:04","timestampInMs":1750455724352,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"4zvnx-1750455724173-01bfba7c00f7","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1058,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNAA0RCRR1KP934638SGE","instanceId":""},{"TimeUTC":"2025-06-20 21:42:04","timestampInMs":1750455724282,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"c6hh2-1750455724106-a8e6e01420e1","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1242,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MNA7VM0ZHSDJ83DPCNVWP","instanceId":""},{"TimeUTC":"2025-06-20 21:42:04","timestampInMs":1750455724055,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"qljlf-1750455721228-66d319ba4d18","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"2/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN7E9BED8GVFZJ7GVY1QQ","instanceId":""},{"TimeUTC":"2025-06-20 21:42:03","timestampInMs":1750455723984,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"qz6x4-1750455721146-8068e4c2b34a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"2/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN7E8H7N2PA6TGEE1C01A","instanceId":""},{"TimeUTC":"2025-06-20 21:42:03","timestampInMs":1750455723447,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":-1,"requestId":"qtv7t-1750455722271-b7cad482edb7","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/wsgi.py\", line 16, in <module>\napplication = get_wsgi_application()\n^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/core/wsgi.py\", line 12, in get_wsgi_application\ndjango.setup(set_prefix=False)\nFile \"/var/task/django/__init__.py\", line 19, in setup\nconfigure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 81, in __getattr__\nself._setup(name)\nFile \"/var/task/django/conf/__init__.py\", line 68, in _setup\nself._wrapped = Settings(settings_module)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/django/conf/__init__.py\", line 166, in __init__\nmod = importlib.import_module(self.SETTINGS_MODULE)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nreturn _bootstrap._gcd_import(name[level:], package, level)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\nFile \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\nFile \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\nFile \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\nFile \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/config/settings.py\", line 25, in <module>\nSECRET_KEY = config(\"SECRET_KEY\")\n^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 248, in __call__\nreturn self.config(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 107, in __call__\nreturn self.get(*args, **kwargs)\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"/var/task/decouple.py\", line 92, in get\nraise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))\ndecouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN8BJVFT3FKRBJWANVMT5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:03","timestampInMs":1750455723442,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"k86rq-1750455723399-32c86b42c87f","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1778,"region":"iad1","maxMemoryUsed":44,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN9DJQBMKSWYEFVPDNCPC","instanceId":""},{"TimeUTC":"2025-06-20 21:42:03","timestampInMs":1750455723422,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"4dcbg-1750455723378-04c58c29f329","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1064,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN9CYWD0WPFKCJ492HYX5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:02","timestampInMs":1750455722357,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"2wfz4-1750455722200-121e391d8e8e","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1070,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN8BNY2TT51YMDECHKXV5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:02","timestampInMs":1750455722354,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"qtv7t-1750455722271-b7cad482edb7","requestUserAgent":"vercel-favicon/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1078,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN8BJVFT3FKRBJWANVMT5","instanceId":""},{"TimeUTC":"2025-06-20 21:42:01","timestampInMs":1750455721417,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"qljlf-1750455721228-66d319ba4d18","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1143,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN7E9BED8GVFZJ7GVY1QQ","instanceId":""},{"TimeUTC":"2025-06-20 21:42:01","timestampInMs":1750455721416,"requestPath":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app/","requestMethod":"GET","requestQueryString":"","responseStatusCode":500,"requestId":"qz6x4-1750455721146-8068e4c2b34a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/config/wsgi.py","host":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentDomain":"docfinance-o9szevvi6-walkerson-souzas-projects.vercel.app","deploymentId":"dpl_EzxgugWnsoT8PzjVJ73k3nVotBWd","durationMs":1053,"region":"iad1","maxMemoryUsed":81,"memorySize":1024,"message":"","projectId":"prj_TAsrezwYpaGNaSOrJ3Ja71auf3Xe","traceId":"","sessionId":"","invocationId":"01JY7MN7E8H7N2PA6TGEE1C01A","instanceId":""}]